### ISSUE TITLE
Failed to activate the ide-html package

### ISSUE THREAD

**Issue by projetmbc** [liuderchi/ide-html#14]
I have just installed the package.

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [ide-html](https://github.com/liuderchi/ide-html) package 0.4.1

### Stack Trace

Failed to activate the ide-html package

```
At EACCES: permission denied, open '/Users/projetmbc/.atom/packages/ide-html/WELCOME_SHOWN'

Error: EACCES: permission denied, open '/Users/projetmbc/.atom/packages/ide-html/WELCOME_SHOWN'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at showWelcomeNotification (/packages/ide-html/src/welcome_notification.js:59:23)
    at /packages/ide-html/src/main.js:12:5)
    at /packages/ide-html/src/main.js:44:18)
    at /packages/ide-html/src/main.js:46:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:242:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:646:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:854:36
```

### Commands

```
     -0:44.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  2x -0:24.9.0 application:open (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-ide-ui 0.5.4 
file-icons 2.1.13 
ide-cpp 0.0.3 
ide-css 0.2.0 
ide-html 0.4.1 
ide-python 0.3.0 
ide-typescript 0.7.0 
language-gfm-enhanced 0.92.0 
language-latex 1.1.1 
latex 0.49.0 
markdown-preview-enhanced 0.15.0 
pdf-view 0.59.0 
script 3.17.3 
```

**Comment by liuderchi** [comment]
@projetmbc Thanks for reporting. What's the file permission of 
`'/Users/projetmbc/.atom/packages/ide-html/WELCOME_SHOWN'` ?

**Comment by projetmbc** [comment]
Indeed I don't have the file.

```
$ cd /Users/projetmbc/.atom/packages/ide-html
$ ls -l
total 96
-rw-r--r--   1 root  staff   1702 15 nov 16:40 CONTRIBUTING.md
-rw-r--r--   1 root  staff   3244 15 nov 16:40 README.md
drwxr-xr-x  15 root  staff    480 15 nov 16:40 node_modules
-rw-r--r--   1 root  staff   7347 15 nov 16:40 package.json
drwxr-xr-x   6 root  staff    192 15 nov 16:40 src
-rw-r--r--   1 root  staff  30216 15 nov 16:40 yarn.lock
```

**Comment by liuderchi** [comment]
@projetmbc Now your packages directory has **root permission** (not often seen), 
however `ide-html` usually do not have such permission.

Please
  1. uninstall `ide-html` or remove `~/.atom/packages/ide-html` manually
  2. start atom without being a super user
  3. install `ide-html` again

reference [code][code] where exception happened

[code]: https://github.com/liuderchi/ide-html/blob/master/src/welcome_notification.js#L59
