### ISSUE TITLE
Uncaught Error: Message header must separate key and value using :

### ISSUE THREAD

**Issue by Verley93** [liuderchi/ide-html#33]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-html](https://github.com/liuderchi/ide-html) package 0.4.2

### Stack Trace

Uncaught Error: Message header must separate key and value using :

```
At C:\Users\Owner\.atom\packages\ide-html\node_modules\vscode-jsonrpc\lib\messageReader.js:68

Error: Message header must separate key and value using :
    at /packages/ide-html/node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (/packages/ide-html/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/packages/ide-html/node_modules/vscode-jsonrpc/lib/messageReader.js:194:43)
    at /packages/ide-html/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
     -5:38.8.0 snippets:next-tab-stop (input.hidden-input)
     -5:38.8.0 snippets:expand (input.hidden-input)
     -5:38.8.0 editor:indent (input.hidden-input)
 18x -5:32.6.0 core:backspace (input.hidden-input)
  2x -3:55.2.0 core:move-right (input.hidden-input)
     -3:54.5.0 core:backspace (input.hidden-input)
     -3:17.5.0 snippets:next-tab-stop (input.hidden-input)
     -3:17.5.0 snippets:expand (input.hidden-input)
     -3:17.5.0 editor:indent (input.hidden-input)
     -3:15.2.0 core:move-up (input.hidden-input)
     -3:13.8.0 editor:newline (input.hidden-input)
     -3:12.8.0 core:move-down (input.hidden-input)
  2x -3:12.5.0 core:move-right (input.hidden-input)
 14x -3:08.9.0 core:backspace (input.hidden-input)
  3x -1:29.6.0 core:delete (input.hidden-input)
     -1:19.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-ide-ui 0.13.0 
autoclose-html 0.23.0 
autocomplete-json 5.5.2 
autocomplete-modules 2.1.0 
fonts 3.1.0 
html-shorcuts-react 3.0.3 
ide-html 0.4.2 
ide-typescript 0.7.6 
language-babel 2.85.0 
language-javascript-jsx 0.3.7 
react 0.18.0 
react-snippets 1.1.1 
```

**Comment by liuderchi** [comment]
@Verley93 thanks for your report!

How does the file you are editing look like?

**Comment by Verley93** [comment]
const clientID = '';
const redirectURI = 'http://localhost:3000/';

let accessToken;

const Spotify = {
    // Check to see if accessToken is already set, or set it w/expiresIn
otherwise
    getAccessToken() {
        if(accessToken) {
            return accessToken;
        }

        // Check URL if Access Token and expiresIn are set
        const matchAccessToken =
window.location.href.match(/access_token=([^&]*)/);
        const matchexpiresIn =
window.location.href.match(/expires_in=([^&]*)/);

        if (matchAcessToken && matchexpiresIn) {
            accessToken = matchAccessToken[1];
            const expiresIn = Number(matchexpiresIn[1]);

            // Set timeout; Wipe accessToken at expiresIn
            window.setTimeout(() => accessToken = '', expiresIn * 1000);
            // Clear parameters from URL to prevent the app from grabbing
accessToken after expiresIn
            window.history.pushState('Access Token', null, '/');
        }
    }
}

export default Spotify;

*Devlin Verley II*
verle006@umn.edu

College of Continuing and Professional Studies
Bachelor of Applied Science, Manufacturing Operations Management
University of Minnesota-Twin Cities
